language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t griffinbrome/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true griffinbrome/docker-react npm run test
